/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package combobox;
import java.util.*;
import javax.swing.JComboBox;
        

/**
 *
 * @author Carolina EM
 */
public class FrCombobox extends javax.swing.JFrame {

    /**
     * Creates new form FrCombobox
     */
    public FrCombobox() {
        initComponents();
        combo1.addItem("Norma");
        combo1.addItem("Carolina");
        combo1.addItem("Luis");
        combo1.addItem("Andrea");
        combo1.addItem("Verónica");
        
        this.setSize(700,600);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResultado = new javax.swing.JTextField();
        combo1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 104, 380, 101));

        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 45, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
        // TODO add your handling code here:
        String nombre=(String)combo1.getSelectedItem();
        if(nombre.equals("Norma")){
            txtResultado.setText("Norma Veronica Ramirez Perez");
        }
        if(nombre.equals("Carolina")){
            txtResultado.setText("Carolina Martínez Espinosa de los Monteros");
        }
        if(nombre.equals("Luis")){
            txtResultado.setText("Luis Rubén Rusiles Leal");
        }
        if(nombre.equals("Andrea")){
            txtResultado.setText("Andrea Hernández Ortega");
        }
        if(nombre.equals("Veronica")){
            txtResultado.setText("Veronica Perez Garcia");
        }
        
    }//GEN-LAST:event_combo1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCombobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
